spring:
  activemq:
    broker-url: tcp://localhost:61616
    password: admin
    user: admin
  jms:
    pub-sub-domain: true
    topic: test-topic
    queue: client.messages
logging:
  level:
    org:
      apache:
        activemq: DEBUG